all:
  children:
    elasticsearch:
      hosts:
        es-node-1:
          ansible_host: 192.168.56.11
          es_node_roles: [master, data]
          ansible_ssh_private_key_file: "{{ inventory_dir }}/../../.vagrant/machines/es-node-1/virtualbox/private_key"
        es-node-2:
          ansible_host: 192.168.56.12
          es_node_roles: [master, data]
          ansible_ssh_private_key_file: "{{ inventory_dir }}/../../.vagrant/machines/es-node-2/virtualbox/private_key"
        es-node-3:
          ansible_host: 192.168.56.13
          es_node_roles: [master, data]
          ansible_ssh_private_key_file: "{{ inventory_dir }}/../../.vagrant/machines/es-node-3/virtualbox/private_key"
      vars:
        ansible_user: vagrant
        ansible_become: true
        ansible_python_interpreter: /usr/bin/python3
